apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  namespace: workloads
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000000"

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-1
  namespace: workloads
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000000"
